### ISSUE TITLE
Renormalized values are counterintuitive (case compressratio)

### ISSUE THREAD

**Issue by riyad** [pdf/zfs_exporter#11]
It seems like the changes made in version 2.0.0 to renormalize values to be between 0..1 seems to produce wrong(?) results:

case in point `compressratio`:
```console
$ zfs list -po name,refcompressratio,logicalreferenced,referenced rpool/crypt/var/log
NAME                 REFRATIO      LREFER       REFER
rpool/crypt/var/log      4.26  6032219136  1445105664
```
 It's clear how the ratio is calculated: `REFRATIO = LREFER/REFER` and it's clear what it means: the "real" data is 4.26 times larger than what's written to disk ... i.e. compression shrunk the data to roughly 1/4 (~24%) of it's original size.

But activating the new metric gives numbers like this:
```
zfs_dataset_compression_ratio{name="rpool/crypt/var/log",pool="rpool",type="filesystem"} 0.7830802603036877
```
I was confused :confused: *After* looking at the formula (i.e. `transformMultiplier()`) I could rationalize that this is the ratio of data that was "compressed away" (i.e. ~ 1 - 0.24) ... which is "not so useful". I'm ok with renormalizing percentages, but "reformulating" ratios is maybe going to far ... while mathematically correct, they *change* their "meaning" (i.e. label <-> number correspondence).

My suggestion would be to remove ratios completely (when they can be calculated from other data: compression, capacity, etc.) or to report them "as is" (i.e. to keep the mental model close to what the CLI reports). Not all ratios are between 0 and 1, nor do they need to be. Whoever uses those ratios will probably know what to do with them (including transformations). :wink:

**Comment by pdf** [comment]
The Prometheus docs recommend that ratios are expressed in the range 0-1, in the same way that bytes is the default data unit, which results in queries being easily applied based on the metric type. In this case, the result is that the compression rate is 78%, though I suppose an argument might be made that this should be expressed as the ratio of compressed size to uncompressed, ie 22%.

Properties like capacity are already reported by ZFS as percentages, it's only compression and dedup ratios that are reported in this multiplier format (which seems like a really odd way of expressing this).

Honestly, I'm not certain what the correct answer is here, I'm going to sleep on it.

**Comment by pdf** [comment]
I think I'm leaning towards using the ratio of compressed space to uncompressed, and updating the help text to reflect that this is what is reported, thoughts?

**Comment by riyad** [comment]
Hmm ... ratios are always tricky (that's why I removed those properties from my PR in one of the later commits in order to avoid a discussion like this :sweat_smile: ).

As a user I'd like to have the data match what zfs gives me (for familiarity with what the number means and what ranges to expect). Plain and simple.

Trying to look at it from a project maintainers perspective I'd suggest 2 possible scenarios:
1. don't expose ratios that can be calculated from other metrics. Let users handle it. Worst case: we can add them later.
2. expose ratios "as is" (with small corrections for e.g. percentages). This would also match the "user perspective" mentioned above.

more "arguments" for the "as is" proposal:
* disk S.M.A.R.T. parameters always expose both the "normal(ized)" and the "raw" value (because somebody will do something "clever" but break expectations/compatibility/comparability)
* stupid analogy: the current formula is like looking at things mirrored (1/x) and from the "back" (1-x) instead of head on which I feel is "disorienting"

I hope this helps navigate the solution space. :sweat_smile:

**Comment by pdf** [comment]
1. I feel a little like like this is kicking the can down the road, and inviting issues asking why these props are not supported. The general recommendation is indeed to avoid exposing ratio metrics when the consituent parts are available, however I don't believe there's a way to calculate `dedupratio`, which means this probably needs solving, at which point we may as well just expose them all.
2. I suppose if I was to do this, I would want to rename the metrics to `_multiplier` or something, since `ratio` has a particular meaning as a base unit for Prometheus/OpenMetrics.

> the current formula is like looking at things mirrored (1/x) and from the "back" (1-x) 

If I was to keep these as ratios, I think I'd change them to be simply "mirrored", rather than both.

I can't say I feel particularly enthusiastic about any of the available options :-/

**Comment by riyad** [comment]
>     1. I feel a little like like this is kicking the can down the road, and inviting issues asking why these props are not supported. The general recommendation is indeed to avoid exposing ratio metrics when the consituent parts are available, however I don't believe there's a way to calculate `dedupratio`, which means this probably needs solving, at which point we may as well just expose them all.

That was the idea. Let time/the people decide if it's important enough to have it exposed "natively".
You're right there're ratios which can't be calculated (IIRC `fragmentation` also). *sigh*

> If I was to keep these as ratios, I think I'd change them to be simply "mirrored", rather than both.

I'd still be in favor of "as is", but only mirrored I could live with. :smile: 

> I can't say I feel particularly enthusiastic about any of the available options :-/

Sorry, to have opened this can of worms. :sweat_smile:

**Comment by pdf** [comment]
I went with retaining them as ratios, but as a ratio of e.g. compressed vs uncompressed size, and tried to clarify the help strings to indicate more clearly what the value means.
