### ISSUE TITLE
go.mod is missing /v2 version suffix

### ISSUE THREAD

**Issue by jstallard** [pdf/zfs_exporter#15]
https://go.dev/ref/mod#major-version-suffixes

This has some other side effects apart from making it inconvenient to import this code in another go module. Installation using `go get` is deprecated as of go 1.17, and will not work starting with go 1.18 (see https://go.dev/doc/go-get-install-deprecation). e.g.

```
% go get -u github.com/pdf/zfs_exporter
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

The `go install` method doesn't currently work because of the missing module suffix:
```
go install github.com/pdf/zfs_exporter@v2.2.2
go install: github.com/pdf/zfs_exporter@v2.2.2: github.com/pdf/zfs_exporter@v2.2.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

Updating go.mod to include the `/v2` version suffix will fix this (starting with the next release).

PR incoming...

**Comment by pdf** [comment]
I have this fixed locally already, I just haven't pushed it up as I didn't think it would be affecting anyone (no downstream code consumers expected, and binaries are available here).

I'll push it up.

**Comment by jstallard** [comment]
Wow talk about quick response time. Obviously feel free to just close my PR if you've already done this, I should've opened the issue before working on it.

It's not affecting much, but I was working on adding a FreeBSD port for this, and the fact that it's not `go install`-able means I can't use a lot of nice wrappers that already exist for making ports out of go modules.

**Comment by pdf** [comment]
Yeah no problem, you've included the doco update in your PR so happy to merge it with the updated commit message.

I really need to update the Github Action to do the SIV update properly when it bumps a major version (which is how this ended up with the missing suffix), I just haven't found the time since testing Actions is super-painful.
