### ISSUE TITLE
failed under supervisor

### ISSUE THREAD

**Issue by tarkhil** [pdf/zfs_exporter#17]
Hello

I've wrote fairly simple supervisor config

```
[program:zfs_exporter]
command=/usr/local/bin/zfs_exporter 
user=nobody
```
and it starts, but upon first request failes
```
ts=2022-01-15T15:04:13.594Z caller=zfs.go:126 level=error msg="Error finding pools" err="exit status 1"
```
without supervisor, it runs just fine. 

I can't even imagine what I've managed to hit. Hoping for any advise

**Comment by pdf** [comment]
You're telling supervisor to run the exporter as `nobody`, my guess is that this user has insufficient privileges to run `zpool`/`zfs` commands on your system.

**Comment by tarkhil** [comment]
It should run as nobody; actually, fetching latest version fixed it.
