### ISSUE TITLE
Exporter does not recover from problems calling the zpool binary

### ISSUE THREAD

**Issue by svalouch** [pdf/zfs_exporter#18]
When the collector fails to call the local binaries, it does not export any metrics indicating the problem and does not recover on its own.

I'm hitting https://github.com/pdf/zfs_exporter/blob/master/collector/zfs.go#L124-L128 where `getPools` fails for some reason, e.g. where the `zpool` binary is missing or exits with a nonzero code. The former has happened during switching between `zfs-kmod` and `zfs-dkms` repositories on a RHEL-based distribution, the latter occurred in a pacemaker-controlled cluster, where pools move between machines (setup roughly based on [zfs-ha](https://github.com/ewwhite/zfs-ha/wiki)) which may sometimes cause a race-condition in which `zpool` seems to exit 1. This is not easy to reproduce, but one can simply remove the `zpool` binary, e.g. by starting with an empty $PATH like so:
```
PATH= ./zfs_exporter
```

Error messages I got were:
* `caller=zfs.go:126 msg="Error finding pools" err="exit status 1"` (pacemaker-cluster)
* `caller=zfs.go:126 msg="Error finding pools" err="exec: \"zpool\": executable file not found in $PATH"` (empty PATH)

In both cases, the exporter won't export anything but the basic go-metrics and its own build version, so the scrape itself still works and the only indicator that something's happened is the sudden absence of metrics, including the `zfs_scrape_collector_success` metrics. The only way I've found that resolves this is to restart the exporter.

**Comment by pdf** [comment]
I think I see why it might get hung up in this case, that should be relatively easy to resolve.

I'm not sure what the correct behaviour for the exporter is in this case though, perhaps we just send `zfs_scrape_collector_success = 0`? Not sure how else we might indicate an error, other than exiting entirely.

**Comment by svalouch** [comment]
Setting the `zfs_scrape_collector_success{collector="$collector"}` metric(s) to`0` should suffice. That way, a simple alarm would be enough to know if it keeps failing for longer, while ignoring short blips that resolve themselves when the causing condition is resolved.

**Comment by pdf** [comment]
Please test v2.2.5 and confirm that it resolves the issue.

**Comment by svalouch** [comment]
Confirmed, both for the binary being missing intermittently and for it returning non-zero intermittently. Thank you very much!
