### ISSUE TITLE
Export scrub/resilver status

### ISSUE THREAD

**Issue by jr0dd** [pdf/zfs_exporter#20]
I was curious if this exports scrub and/or resilvering status? I briefly dig through the code and didn't see anything that stuck out. ZED is very flaky in general and it would be so awesome to be able to dump that and have alerts through Prometheus.

**Comment by pdf** [comment]
It doesn't - I made the decision to rely on the CLI for data as that provides the broadest compatibility across operating systems/versions. The downside is that the CLI tools do not support machine-readable output for some data points, and I've not been motivated to attempt the more brittle text parsing required to export such data.

Ref #5

**Comment by jr0dd** [comment]
> It doesn't - I made the decision to rely on the CLI for data as that provides the broadest compatibility across operating systems/versions. The downside is that the CLI tools do not support machine-readable output for some data points, and I've not been motivated to attempt the more brittle text parsing required to export such data.
> 
> 
> 
> Ref #5

Ok. No biggie.
