### ISSUE TITLE
Question - Problems Adding Pools

### ISSUE THREAD

**Issue by norsemanGrey** [pdf/zfs_exporter#23]
I have an issue filtering/adding the pools I want to collect data from. I think I might be using the flag incorrectly.  From the Readme I understood the usage like this:

```
    --pool="fastpool-1" \
    --pool="slowpool-1" \
```

**Comment by pdf** [comment]
That's correct, what problem are you experiencing?

**Comment by norsemanGrey** [comment]
Thanks for confirming. I do not know what was wrong. After removing that part of the config, restarting the service, putting the config back and restarting yet again it worked. Might have been a glitch.
