### ISSUE TITLE
Error parsing Pool fragmentation

### ISSUE THREAD

**Issue by ymasson** [pdf/zfs_exporter#26]
Hi,

With `--collector.pool` enabled.
On ZoF or ZoL (before OpenZFS 2), I have
```
level=error ts=2023-01-27T16:10:06.365Z caller=zfs.go:219 msg="Executing collector" status=error collector=pool durationSeconds=0.005495284 err="strconv.ParseFloat: parsing \"0%\": invalid syntax"
level=error ts=2023-01-27T16:11:31.411Z caller=zfs.go:219 msg="Executing collector" status=error collector=pool durationSeconds=0.005649248 err="strconv.ParseFloat: parsing \"1.00x\": invalid syntax"
```
because:
```
# zpool get -Hpo name,property,value dedupratio,fragmentation
backup	dedupratio	1.00x
backup	fragmentation	0%
```
No problem on OpenZFS 2.

I propose to add the minimal ZFS version suported in README, or add the support for older version.

Thanks

**Comment by pdf** [comment]
Thanks for the report. I fixed fragmentation in v2.2.5, but didn't notice in your description that dedupratio also produces nonstandard output on those versions. Give me a moment and I'll publish v2.2.6 to fix that as well.
