### ISSUE TITLE
Official container image for this exporter?

### ISSUE THREAD

**Issue by linkvt** [pdf/zfs_exporter#27]
Hi,

I just noticed, that this exporter provides no official container image and was not sure, if I could grab this task.

Altough it might not make sense to run this exporter in a container at first, it seems to be possible when running the container with zfs installed in privileged mode - mounting `/dev/zfs` alone did not do the trick.
I would assume that this is mostly safe as the commands executed in https://github.com/pdf/zfs_exporter/blob/master/zfs/pool.go are only reading, but I don't know for sure what is happening in the background.

Did you think about this already and is there maybe a good reason to not run the exporter in a container?

Thanks!

**Comment by pdf** [comment]
Yes, this exporter supports many platforms, and relies on the host's version of the ZFS tooling, otherwise you may have incompatibilities between your ZFS pool version/caps and ZFS CLI.

Maintaining a full matrix of containers for all the possible OS and ZFS tool versions would be... possible, but complex.

**Comment by linkvt** [comment]
Makes perfect sense, thanks for the explanation!

**Comment by tschoening81** [comment]
> Altough it might not make sense to run this exporter in a container at first, it seems to be possible when running the container with zfs installed in privileged mode - mounting /dev/zfs alone did not do the trick.

Which container image did you use for your tests? I didn't find a too good fitting image providing basically ZFS-only and built a custom one based on UB 25.04.

Additionally, while I often read is as well, I don't seem to require privileged mode with the container, forwarding `/dev/zfs` seems to be enough. I'm wondering if things don't work under the hood and only look working or something. :-)
