### ISSUE TITLE
Inconsistent results with zfs list

### ISSUE THREAD

**Issue by lyz-code** [pdf/zfs_exporter#31]
Hi, I'm comparing the results of the metrics with the result of `zfs list -o name,used,avail,refer,usedds,usedsnap,lused ` and I don't know why  the results are different.

```
# zfs list -o name,used,avail,refer,usedds,usedsnap,lused 
NAME          USED  AVAIL     REFER  USEDDS  USEDSNAP  LUSED
main/lyz     61.5G  41.6G     37.4G   37.4G     24.1G  86.9G
```

The dataset `main/lyz` doesn't have any children.

So far I think that the correlation between the metrics exposed by the exporter and the `zfs list` columns are:

- USED: `zfs_dataset_used_bytes`, shows 66.02G instead of 61.5G
- AVAIL: `zfs_dataset_available_bytes{name="main/lyz",type="filesystem"}`, shows 44.5G instead of 41.6G
- LUSED: `zfs_dataset_logical_used_bytes{type="filesystem"}`, shows 93.34G instead of 86.9G
- USEDDS: `zfs_dataset_used_by_dataset_bytes="filesystem"}`, shows 40.11G instead of 37.4G
- USEDSNAP: `zfs_dataset_used_bytes - zfs_dataset_used_by_dataset_bytes` shows 25G instead of 24.1G. This doesn't work for datasets that have children. An alternative metric could be `sum by (hostname,filesystem) (zfs_dataset_used_bytes{type='snapshot'})` which shows 13.1G.

What can be the reason behind this differences? I've repeated the commands throughout time and the results are the same as the data in the dataset has not changed between runs

**Comment by pdf** [comment]
The exporter collects usage in bytes. When viewing metrics in e.g. Grafana, make sure you're choosing the base unit that will produce the unit conversions you expect (SI for units of 1000, IEC for units of 1024).

HDD manufacturers tend use SI to make their capacity numbers larger, but most other applications use IEC (e.g. operating systems).
