### ISSUE TITLE
Add more usedby properties

### ISSUE THREAD

**Issue by lyz-code** [pdf/zfs_exporter#32]
It would be awesome to have access to `usedbysnapshots` and `usedbychildren`. I have no idea of Go, but if you guide me a little bit I can try to make a pull request

**Comment by pdf** [comment]
These properties are available, simply specify them on the command-line for the collectors you wish to enable them on, these are the defaults:

```
      --properties.dataset-filesystem="available,logicalused,quota,referenced,used,usedbydataset,written"  
      --properties.dataset-snapshot="logicalused,referenced,used,written"  
      --properties.dataset-volume="available,logicalused,referenced,used,usedbydataset,volsize,written"  
```

Most properties are supported, if you find any that aren't, feel free to raise an issue. You can see the supported properties here:

https://github.com/pdf/zfs_exporter/blob/dd8adbea7e5fe3df2089a88c94c26f7d8e443e5d/collector/dataset.go#L24
